services:
  app:
    image: ghcr.io/html5syt/Gen-AI-API-Key-Hunt:latest
    pull_policy: always
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data:/app/data
    restart: unless-stopped
